### ISSUE TITLE
Make frontend for login and signup pages

### ISSUE THREAD

**Issue by asadrajput2** [asadrajput2/smart-shopping-cart#2]
The current frontend for Login and Signup pages is the bare-minimum for testing purposes. They are to be written properly in React and designed accordingly. The current version functions properly, only the design needs to be improved.

Pages are available at `frontend/src/components/`

**Comment by TanishqHarjani** [comment]
[signin and signup for screenshots.zip](https://github.com/asadrajput2/smart-shopping-cart/files/5678927/signin.and.signup.for.screenshots.zip)
